name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]  # keep 3.11 only until green; add 3.10 later
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Show environment
        run: |
          python -V
          pip -V
          ls -la
          echo "Repo tree:"
          find . -maxdepth 2 -type f | sort

      - name: Install dependencies (app + dev)
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip freeze | sort

      # ---- Lint & style ----
      - name: Black (check only)
        run: black app.py tests --check

      - name: Ruff (lint)
        run: ruff check app.py tests --output-format=github

      # ---- Tests ----
      - name: Pytest
        env:
          PYTHONWARNINGS: ignore::DeprecationWarning
        run: |
          pytest -q -rA
