name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install app dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dev dependencies (incl. pre-commit)
        run: |
          pip install -r requirements-dev.txt
          pip install pre-commit

      # --------------------------------
      # Pre-commit (runs configured hooks)
      # --------------------------------
      - name: Pre-commit (all files)
        run: |
          pre-commit --version
          pre-commit run --all-files

      # --------------------------------
      # Code style & linting (explicit)
      # --------------------------------
      - name: Black (check only)
        run: |
          black --version
          black . --check

      - name: Ruff (lint)
        run: |
          ruff --version
          ruff check . --output-format=github

      # ----------------------
      # Unit tests
      # ----------------------
      - name: Pytest
        env:
          PYTHONWARNINGS: ignore::DeprecationWarning
        run: |
          pytest -q
